// 40 Indian cities, weighted by typical e-commerce order share.
export const CITIES: { name: string; weight: number }[] = [
  { name: "Mumbai", weight: 12 },
  { name: "Delhi", weight: 11 },
  { name: "Bengaluru", weight: 10 },
  { name: "Pune", weight: 9 },
  { name: "Hyderabad", weight: 7 },
  { name: "Chennai", weight: 6 },
  { name: "Kolkata", weight: 5 },
  { name: "Ahmedabad", weight: 4 },
  { name: "Jaipur", weight: 3 },
  { name: "Lucknow", weight: 3 },
  { name: "Indore", weight: 2 },
  { name: "Nagpur", weight: 2 },
  { name: "Bhopal", weight: 2 },
  { name: "Chandigarh", weight: 2 },
  { name: "Surat", weight: 2 },
  { name: "Kochi", weight: 2 },
  { name: "Coimbatore", weight: 2 },
  { name: "Visakhapatnam", weight: 2 },
  { name: "Vadodara", weight: 1 },
  { name: "Patna", weight: 1 },
  { name: "Ludhiana", weight: 1 },
  { name: "Kanpur", weight: 1 },
  { name: "Nashik", weight: 1 },
  { name: "Mysuru", weight: 1 },
  { name: "Thiruvananthapuram", weight: 1 },
  { name: "Guwahati", weight: 1 },
  { name: "Raipur", weight: 1 },
  { name: "Ranchi", weight: 1 },
  { name: "Jodhpur", weight: 1 },
  { name: "Varanasi", weight: 1 },
  { name: "Agra", weight: 1 },
  { name: "Madurai", weight: 1 },
  { name: "Amritsar", weight: 1 },
  { name: "Faridabad", weight: 1 },
  { name: "Gurugram", weight: 1 },
  { name: "Noida", weight: 1 },
  { name: "Thane", weight: 1 },
  { name: "Navi Mumbai", weight: 1 },
  { name: "Goa", weight: 1 },
  { name: "Dehradun", weight: 1 },
];
